name: WeChatSwift
options:
  bundleIdPrefix: com.study
  deploymentTarget:
    iOS: "15.1"
  developmentLanguage: zh-Hans

targets:
  WeChatSwiftTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - WeChatSwiftTests
    dependencies:
      - target: WeChatSwift
    settings:
      base:
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/WeChatSwift.app/WeChatSwift
        PRODUCT_BUNDLE_IDENTIFIER: com.study.wcSwiftTests
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2DAFKPU228
        GENERATE_INFOPLIST_FILE: YES

  WeChatSwift:
    type: application
    platform: iOS
    sources:
      - WeChatSwift
    info:
      path: WeChatSwift/Info.plist
      properties:
        CFBundleDevelopmentRegion: zh_CN
        CFBundleDisplayName: 微信
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIUserInterfaceStyle: Light
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        NSCameraUsageDescription: 用于扫一扫识别二维码
        NSPhotoLibraryUsageDescription: 用于从相册选取图片识别二维码
        RCTNewArchEnabled: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.study.wcSwift
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: WeChatSwift/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2DAFKPU228
      configs:
        Debug:
          ENABLE_DEBUG_DYLIB: "NO"

schemes:
  WeChatSwift:
    build:
      targets:
        WeChatSwift: all
        WeChatSwiftTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - WeChatSwiftTests
    archive:
      config: Release
